musl: Fix ldd symlink install in case of multilib
Otherwise dnf install lib32-musl and musl will fail with below error:

  ERROR: core-image-sato-1.0-r0 do_rootfs: Could not invoke dnf.
  ...
  Error: Transaction check error:
    file /usr/bin/ldd.musl conflicts between attempted installs of \
  musl-1.1.20+git0+39ef612aa1-r0.ppc64p8 and \
  lib32-musl-1.1.20+git0+39ef612aa1-r0.ppcp8
  ...

Signed-off-by: Serhey Popovych <serhe.popovych@gmail.com>